apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabtech-web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: fabtech-web
  template:
    metadata:
      labels:
        app: fabtech-web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: fabtech-web
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          env:
            - name: CONTENT_API_URL
              value: {{ .Values.web.contentApiUrl | quote }}
          ports:
            - containerPort: {{ .Values.web.service.port }}
          resources: {{ toYaml .Values.web.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          {{- if .Values.sharedStorage.enabled }}
          volumeMounts:
            - name: shared-content
              mountPath: {{ .Values.sharedStorage.mountPath | quote }}
              readOnly: false
          {{- end }}
      {{- if .Values.sharedStorage.enabled }}
      volumes:
        - name: shared-content
          persistentVolumeClaim:
            claimName: {{ .Values.sharedStorage.existingClaim | quote }}
      {{- end }}
