apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: c09-shared-files
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS
  protocol: smb
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
  - uid=100
  - gid=100
  - dir_mode=0770
  - file_mode=0660
  - mfsymlinks
  - nosharesock
  - actimeo=30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: c09-shared-content
  namespace: fabtech
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteMany]
  storageClassName: c09-shared-files
  resources:
    requests:
      storage: 5Gi