apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - secretproviderclass.yaml
  - security-networkpolicy.yaml
  - c09-postgresql.yaml
  - c09-shared-storage.yaml