apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fabtech-secrets
  namespace: fabtech
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "fc248ea0-3df7-4046-a786-3a3153adc60e"
    keyvaultName: "kv-fabtech-1789472326"
    tenantId: "9b1d3cd8-5db7-4564-905d-4d2eba7b66d5"
    objects: |
      array:
        - |
          objectName: db-connection-string
          objectType: secret
          objectVersion: ""