apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fabtech
  namespace: cluster-config
spec:
  interval: 1m
  timeout: 5m
  releaseName: fabtech
  targetNamespace: fabtech
  storageNamespace: fabtech
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          group: apps
          version: v1
          kind: Deployment
          name: fabtech-api
          namespace: fabtech
  chart:
    spec:
      chart: ./Student/Resources/src/manifests/chart
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: cluster-config
        namespace: cluster-config
  values:
    sharedStorage:
      enabled: true
      existingClaim: c09-shared-content-mi
      mountPath: /mnt/shared
    api:
      image:
        repository: acraksab.azurecr.io/content-api
        tag: v2
      autoscaling:
        enabled: true
      serviceAccountName: fabtech-api-sa
      database:
        secretProviderClass: fabtech-secrets
    web:
      image:
        repository: acraksab.azurecr.io/content-web
        tag: v1
      replicaCount: 3